package thaumcraft.common;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;

public class ThaumcraftSounds {
    public static class ResourceLocations {
        public static final ResourceLocation RES_RUNIC_SHIELD_CHARGE = new ResourceLocation(Thaumcraft.MOD_ID,"runic_shield_charge");
        public static final ResourceLocation RES_CRYSTAL = new ResourceLocation(Thaumcraft.MOD_ID,"crystal");
        public static final ResourceLocation RES_GORE = new ResourceLocation(Thaumcraft.MOD_ID,"gore");
        public static final ResourceLocation RES_LEARN = new ResourceLocation(Thaumcraft.MOD_ID,"learn");
        public static final ResourceLocation RES_CAMERA_TICKS = new ResourceLocation(Thaumcraft.MOD_ID,"cameraticks");
        public static final ResourceLocation RES_RUMBLE = new ResourceLocation(Thaumcraft.MOD_ID,"rumble");
        public static final ResourceLocation RES_FLY = new ResourceLocation(Thaumcraft.MOD_ID,"fly");
        public static final ResourceLocation RES_SPILL = new ResourceLocation(Thaumcraft.MOD_ID,"spill");
        public static final ResourceLocation RES_HEARTBEAT = new ResourceLocation(Thaumcraft.MOD_ID,"heartbeat");
        public static final ResourceLocation RES_ZAP = new ResourceLocation(Thaumcraft.MOD_ID,"zap");
        public static final ResourceLocation RES_TOOL = new ResourceLocation(Thaumcraft.MOD_ID,"tool");
        public static final ResourceLocation RES_CRAFT_FAIL = new ResourceLocation(Thaumcraft.MOD_ID,"craftfail");
        public static final ResourceLocation RES_ROOTS = new ResourceLocation(Thaumcraft.MOD_ID,"roots");
        public static final ResourceLocation RES_DOOR_FAIL = new ResourceLocation(Thaumcraft.MOD_ID,"doorfail");
        public static final ResourceLocation RES_PUMP = new ResourceLocation(Thaumcraft.MOD_ID,"pump");
        public static final ResourceLocation RES_ICE = new ResourceLocation(Thaumcraft.MOD_ID,"ice");
        public static final ResourceLocation RES_JACOBS = new ResourceLocation(Thaumcraft.MOD_ID,"jacobs");
        public static final ResourceLocation RES_ALEMBIC_KNOCK = new ResourceLocation(Thaumcraft.MOD_ID,"alembicknock");
        public static final ResourceLocation RES_PAGE = new ResourceLocation(Thaumcraft.MOD_ID,"page");
        public static final ResourceLocation RES_BUBBLE = new ResourceLocation(Thaumcraft.MOD_ID,"bubble");
        public static final ResourceLocation RES_JAR = new ResourceLocation(Thaumcraft.MOD_ID,"jar");
        public static final ResourceLocation RES_WHISPERS = new ResourceLocation(Thaumcraft.MOD_ID,"whispers");
        public static final ResourceLocation RES_BRAIN = new ResourceLocation(Thaumcraft.MOD_ID,"brain");
        public static final ResourceLocation RES_CREAK = new ResourceLocation(Thaumcraft.MOD_ID,"creak");
        public static final ResourceLocation RES_SQUEEK = new ResourceLocation(Thaumcraft.MOD_ID,"squeek");
        public static final ResourceLocation RES_URN_BREAK = new ResourceLocation(Thaumcraft.MOD_ID,"urnbreak");
        public static final ResourceLocation RES_EVIL_PORTAL = new ResourceLocation(Thaumcraft.MOD_ID,"evilportal");
        public static final ResourceLocation RES_CRAFT_START = new ResourceLocation(Thaumcraft.MOD_ID,"craftstart");
        public static final ResourceLocation RES_INFUSER_START = new ResourceLocation(Thaumcraft.MOD_ID,"infuserstart");
        public static final ResourceLocation RES_INFUSER = new ResourceLocation(Thaumcraft.MOD_ID,"infuser");
        public static final ResourceLocation RES_WAND = new ResourceLocation(Thaumcraft.MOD_ID,"wand");
        public static final ResourceLocation RES_RUNIC_SHIELD_EFFECT = new ResourceLocation(Thaumcraft.MOD_ID,"runic_shield_effect");
        public static final ResourceLocation RES_WAND_FAIL = new ResourceLocation(Thaumcraft.MOD_ID,"wandfail");
        public static final ResourceLocation RES_SWING = new ResourceLocation(Thaumcraft.MOD_ID,"swing");
        public static final ResourceLocation RES_WIND = new ResourceLocation(Thaumcraft.MOD_ID,"wind");
        public static final ResourceLocation RES_KEY = new ResourceLocation(Thaumcraft.MOD_ID,"key");
        public static final ResourceLocation RES_COINS = new ResourceLocation(Thaumcraft.MOD_ID,"coins");
        public static final ResourceLocation RES_FIRE_LOOP = new ResourceLocation(Thaumcraft.MOD_ID,"fireloop");
    }

    public static final SoundEvent RUNIC_SHIELD_CHARGE = SoundEvent.createFixedRangeEvent(ResourceLocations.RES_RUNIC_SHIELD_CHARGE,16.F);
    public static final SoundEvent CRYSTAL = SoundEvent.createFixedRangeEvent(ResourceLocations.RES_CRYSTAL,16.F);
    public static final SoundEvent GORE = SoundEvent.createFixedRangeEvent(ResourceLocations.RES_GORE,16.F);
    public static final SoundEvent LEARN = SoundEvent.createFixedRangeEvent(ResourceLocations.RES_LEARN,16.F);
    public static final SoundEvent CAMERA_TICKS = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_CAMERA_TICKS);
    public static final SoundEvent RUMBLE = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_RUMBLE);
    public static final SoundEvent FLY = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_FLY);
    public static final SoundEvent SPILL = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_SPILL);
    public static final SoundEvent HEARTBEAT = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_HEARTBEAT);
    public static final SoundEvent ZAP = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_ZAP);
    public static final SoundEvent TOOL = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_TOOL);
    public static final SoundEvent CRAFT_FAIL = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_CRAFT_FAIL);
    public static final SoundEvent ROOTS = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_ROOTS);
    public static final SoundEvent DOOR_FAIL = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_DOOR_FAIL);
    public static final SoundEvent PUMP = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_PUMP);
    public static final SoundEvent ICE = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_ICE);
    public static final SoundEvent JACOBS = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_JACOBS);
    public static final SoundEvent ALEMBIC_KNOCK = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_ALEMBIC_KNOCK);
    public static final SoundEvent PAGE = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_PAGE);
    public static final SoundEvent BUBBLE = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_BUBBLE);
    public static final SoundEvent JAR = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_JAR);
    public static final SoundEvent WHISPERS = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_WHISPERS);
    public static final SoundEvent BRAIN = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_BRAIN);
    public static final SoundEvent CREAK = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_CREAK);
    public static final SoundEvent SQUEEK = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_SQUEEK);
    public static final SoundEvent URN_BREAK = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_URN_BREAK);
    public static final SoundEvent EVIL_PORTAL = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_EVIL_PORTAL);
    public static final SoundEvent CRAFT_START =  SoundEvent.createVariableRangeEvent(ResourceLocations.RES_CRAFT_START);
    public static final SoundEvent INFUSER_START = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_INFUSER_START);
    public static final SoundEvent INFUSER = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_INFUSER);
    public static final SoundEvent WAND = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_WAND);
    public static final SoundEvent RUNIC_SHIELD_EFFECT = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_RUNIC_SHIELD_EFFECT);
    public static final SoundEvent WAND_FAIL = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_WAND_FAIL);
    public static final SoundEvent SWING = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_SWING);
    public static final SoundEvent WIND = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_WIND);
    public static final SoundEvent KEY = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_KEY);
    public static final SoundEvent COINS = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_COINS);
    public static final SoundEvent FIRE_LOOP = SoundEvent.createVariableRangeEvent(ResourceLocations.RES_FIRE_LOOP);
}
